site_name: "Mininterface"
repo_name: CZ-NIC/mininterface
repo_url: https://github.com/CZ-NIC/mininterface
docs_dir: docs

theme:
  name: "material"
  features: navigation.expand

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            show_source: false
            members_order: source
            show_bases: false
            show_labels: false
            show_root_heading: true
            heading_level: 3

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true # highlight code during build time, not in javascript
      linenums: false # enable line numbering
      linenums_style: pymdownx-inline # how lines are numbered
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences: # make exceptions to highlighting of code:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.keys # keyboard keys
  - tables
  - footnotes

nav:
  - Introduction: index.md
  - Overview.md
  - Supported-types.md
  - Examples.md
  - API:
      - run.md
      - Mininterface.md
      - Tag.md
      - Facet.md
      - Subcommands.md
      - Custom types:
          - Tag-subclasses.md
          - Tag-aliases.md
          - Prepared-annotations.md
  - Extras:
      - Settings.md
      - Exceptions.md
      - Interfaces.md
      - Standalone.md
      - Helper-types.md
      - Validation.md
      - Experimental.md
  - Changelog.md
  - Dev-guide.md
