name: Upload Python Package
on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'
      - '[0-9].[0-9].[0-9]-rc.[0-9]'

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          password: ${{ secrets.PYPI_GITHUB_MININTERFACE }}