name: tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.10", 3.11, 3.12, 3.13]
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install minimal dependencies
        run: pip install -e .
      - name: Run minimal tests
        # It is important to test the minimal installation
        # as it should be the most stable one which can be thwarted by a single errand import.
        #
        # Even though it is a complex task to neglect some dependencies from being importable,
        # it is easy to not install them at all.
        run: python3 -m unittest tests.minimal_test
      - name: Install dependencies
        run: |
          pip install -e .[basic]
          # dev-dependencies from pyproject.toml
          pip install attrs
          pip install pydantic
      - name: Run tests
        run: python3 -m unittest discover -s tests -p "test_*.py"
